controllers:
  config:
    body: {cascaded_position: false, command: body_command, dynamic_reconfigure: true,
      setpoint: body_setpoint, state: body_state}
  pitch:
    position: {d: 0, i: 0, p: 2}
    velocity: {d: 0, i: 0, p: 2}
  roll:
    position: {d: 0, i: 0, p: 2}
    velocity: {d: 0, i: 0, p: 2}
  x:
    position: {d: 0, i: 0, p: 2}
    velocity: {d: 0, i: 0, p: 2}
  y:
    position: {d: 0, i: 0, p: 2}
    velocity: {d: 0, i: 0, p: 2}
  yaw:
    position: {d: 0, i: 0, p: 2}
    velocity: {d: 0, i: 0, p: 2}
  z:
    position: {d: 0, i: 0, p: 2}
    velocity: {d: 0, i: 0, p: 2}
